### ISSUE TITLE
Incorrect orientation in vertical aspect ratio

### ISSUE THREAD

**Issue by felleg** [nullobject/Arcade-Cave_MiSTer#12] opened 2020-08-31 01:13 UTC
I compared the orientation with other upright games (donkey kong, pac-man) and I noticed the screen is flipped compared to these. I don't know if there is a standard in MiSTer for upright games, or if that's what the known bug "Missing menu settings for aspect ratio, screen orientation, flipping, etc." is describing, but I just thought I'd point it out.

**Comment by nullobject** [comment] 2020-08-31 03:18
@felleg It is a known issue, but it helps to have a ticket for it. Thanks :+1:

**Comment by Manuarcademaniac** [comment] 2020-09-09 06:34
The orientación its correct. I had the original jamma PCB. Most of vertical games has a anti clockwise orientation by default.. Only some classic like Pacman or bombjack has clockwise orientation and can't changed. THIS IS NOT A BUG on Dodonpachi but the
Dep switches probably has a flip option for clockwise orientation.

**Comment by zakk4223** [comment] 2020-12-13 09:50
Dodonpachi has a screen flip option in the test menu, which I'm not sure is implemented yet.

**Comment by nullobject** [comment] 2020-12-13 23:06
@zakk4223 No, not yet.

**Comment by nullobject** [comment] 2021-01-02 05:54
This has been fixed in beta 4. There are now options for changing the orientation in the MiSTer menu.

**Closed by nullobject** 2021-01-02 05:54 UTC
Labels: enhancement
